<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(1)_layered_id_attribute_group_3</name>
   <tag></tag>
   <elementGuidId>e539f71f-9736-4633-a0be-2d6ba75d21d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#layered_id_attribute_group_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='layered_id_attribute_group_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e8e26a1-dade-4384-af60-91f475640bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8a46fc47-9c73-4f7d-9d6f-c9ef91778273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ad85f11c-ee5c-4712-89cd-ac197984e902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>layered_id_attribute_group_3</value>
      <webElementGuid>07e3d055-0fdc-48e9-9621-48cbf1aa47d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>layered_id_attribute_group_3</value>
      <webElementGuid>4e37390c-faac-4d19-9f58-6dcd6f52beaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3_1</value>
      <webElementGuid>4cb81b4a-e796-420f-b59b-f69cb64d96e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layered_id_attribute_group_3&quot;)</value>
      <webElementGuid>51f7b811-724d-4e32-8870-74f2ca11646d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='layered_id_attribute_group_3']</value>
      <webElementGuid>c33a5ae0-a1d4-464c-ac4a-61f986edc20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-layered_id_attribute_group_3']/span/input</value>
      <webElementGuid>0c2c4909-6c0e-4415-8cda-e04ac5a1cc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/span/input</value>
      <webElementGuid>031f2dad-ee60-40a0-99ab-3a0c8bd439d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'layered_id_attribute_group_3' and @id = 'layered_id_attribute_group_3']</value>
      <webElementGuid>e52bac02-d687-4776-ada8-fcb4a3c7206b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
