<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Importo_1</name>
   <tag></tag>
   <elementGuidId>984006a4-d268-4b2c-8733-552cdc0edce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ajax_block_products_total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer_cart']/div/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf7ed93b-987c-4f50-8a1f-4c8818902260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax_block_products_total</value>
      <webElementGuid>a6266194-88be-4e3e-b540-b93eb8126583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$16.51</value>
      <webElementGuid>be7d93e9-c4e8-4362-8b39-4a336995c533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer_cart&quot;)/div[@class=&quot;clearfix&quot;]/div[@class=&quot;layer_cart_cart col-xs-12 col-md-6&quot;]/div[@class=&quot;layer_cart_row&quot;]/span[@class=&quot;ajax_block_products_total&quot;]</value>
      <webElementGuid>708d4f8b-ca67-4d17-ac8a-8b242eab43dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer_cart']/div/div[2]/div/span</value>
      <webElementGuid>3eaac956-80fd-4364-be27-1017354ec547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total products'])[1]/following::span[1]</value>
      <webElementGuid>9dfd9bd9-f43d-4197-b066-f3d31c4e717e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There is 1 item in your cart.'])[1]/following::span[1]</value>
      <webElementGuid>d6da3f28-5458-4f55-9d5a-3c633fff41df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2.00'])[2]/preceding::span[1]</value>
      <webElementGuid>d3e66064-86db-4f6d-9b15-e457b0fa6a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>8ebe4024-4d2a-4546-8a58-ff19e5c2b0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$16.51' or . = '$16.51')]</value>
      <webElementGuid>e20ff149-d77e-43fb-b945-1adaf589f394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
