<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Faded Short Sleeve T-shirts</name>
   <tag></tag>
   <elementGuidId>b083b0a2-b95a-4171-b040-9e8ed62b2066</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#layer_cart_product_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='layer_cart_product_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>20878fcc-2a00-4059-9ad0-d6a08f76e9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>layer_cart_product_title</value>
      <webElementGuid>fe05b3c8-fc37-4fc0-964a-361aa0e9d12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-name</value>
      <webElementGuid>982a55f3-5a7e-416a-8ed3-010edc7585d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Faded Short Sleeve T-shirts</value>
      <webElementGuid>679adde6-8d69-4df2-958c-bf3a847e956c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layer_cart_product_title&quot;)</value>
      <webElementGuid>ace1ac0e-6512-4e29-9c98-508ba3b2f7c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='layer_cart_product_title']</value>
      <webElementGuid>69929ce7-a73b-4103-990a-43c63c43f2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layer_cart']/div/div/div[2]/span</value>
      <webElementGuid>26a370cc-37c9-44f5-b4aa-3fb363b89f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check out'])[1]/following::span[2]</value>
      <webElementGuid>8b32d6e9-0ef3-4650-a982-a995a6a10488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orange, S'])[2]/preceding::span[1]</value>
      <webElementGuid>140f2faf-2c68-41ee-baef-f6fd992bdd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::span[2]</value>
      <webElementGuid>6981d3d5-86c5-4a78-8ef8-d73351060a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Faded Short Sleeve T-shirts']/parent::*</value>
      <webElementGuid>c015e03e-cd49-4dcf-895e-13ccb7ffc221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/span</value>
      <webElementGuid>51b30c43-56bc-4870-8f5e-54ba1dfa650d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'layer_cart_product_title' and (text() = 'Faded Short Sleeve T-shirts' or . = 'Faded Short Sleeve T-shirts')]</value>
      <webElementGuid>840491d7-2d4a-403a-9f27-dc5dd64307cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
