<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_2.00_cgv</name>
   <tag></tag>
   <elementGuidId>d95d8133-c793-4787-bdf5-69f8f37b9a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cgv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cgv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32bd8349-a881-410b-acbf-a93b0593f04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9a68d47c-37fb-43fe-9ead-013dc2c56678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cgv</value>
      <webElementGuid>d8d28f20-302e-4112-a12a-a43e16205f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cgv</value>
      <webElementGuid>845a9099-9c4a-4488-84ef-74440afc08e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1ea78bf1-19cd-419d-99cd-1b3209142e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cgv&quot;)</value>
      <webElementGuid>750e9b2a-6d55-4128-961c-1826367f59c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cgv']</value>
      <webElementGuid>33ec0c82-7207-4b73-a6b6-404c4479c8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uniform-cgv']/span/input</value>
      <webElementGuid>cb09d599-0d41-4e11-b290-18d2cbb505d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/div/span/input</value>
      <webElementGuid>481b1713-9581-41d1-9ccf-03385af7c487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'cgv' and @id = 'cgv']</value>
      <webElementGuid>c570cdcb-9b2c-4b2a-9081-ac88fe8f907a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
