<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Importo</name>
   <tag></tag>
   <elementGuidId>d2738b00-af3f-4438-980b-e973c05db666</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total_product_price_1_1_757718</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='total_product_price_1_1_757718']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>08288d4b-0cb1-4303-ad83-16db0527da43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>7d2a7108-e986-4d2b-aa98-2a8b7deec778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_product_price_1_1_757718</value>
      <webElementGuid>abf939ea-1d0f-4293-9371-19aa489cef6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												$16.51									</value>
      <webElementGuid>e3397b98-8088-4e92-ac2b-9437fb99af1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total_product_price_1_1_757718&quot;)</value>
      <webElementGuid>f5e6ea05-dd8a-44e8-9a8c-2f71c5621607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='total_product_price_1_1_757718']</value>
      <webElementGuid>1912543a-453e-496c-a38e-feca630a6cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='product_1_1_0_757718']/td[6]/span</value>
      <webElementGuid>e898a0d9-6fea-4eeb-9bea-c6a9791b2ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$16.51'])[5]/following::span[3]</value>
      <webElementGuid>808a3e73-7156-45f2-9e93-bc47925f2b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In stock'])[1]/following::span[5]</value>
      <webElementGuid>d6dc8fcd-a193-481e-84cf-5fa383fdfc12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(My address)'])[1]/preceding::span[1]</value>
      <webElementGuid>e42b32f4-351f-475e-81f1-f6c459ff8d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span</value>
      <webElementGuid>1b75390a-9e0e-451b-b29e-53288f882112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'total_product_price_1_1_757718' and (text() = '
												$16.51									' or . = '
												$16.51									')]</value>
      <webElementGuid>34876aa5-a7aa-49d0-8de5-18ba498b6439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
