<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Totale</name>
   <tag></tag>
   <elementGuidId>56e7017d-670f-4693-a29c-f6dfd9bfa64f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total_price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='total_price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dd8f35af-9654-40af-b1d6-be90fca3a5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_price</value>
      <webElementGuid>40a3d5fe-9a62-41f4-8839-7106e0899d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$19.25</value>
      <webElementGuid>3f25e736-5a19-4c0e-94bf-fe8aaa37f608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total_price&quot;)</value>
      <webElementGuid>78363c38-c5f6-4537-b95c-4daac46eb109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='total_price']</value>
      <webElementGuid>b33dd5b9-69f5-4489-9542-9d7a8a1d2f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='total_price_container']/span</value>
      <webElementGuid>501da847-6fcc-4f17-95a0-6476c5517fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[6]/following::span[1]</value>
      <webElementGuid>3f671d3b-8da4-4045-ac47-b5cab2781d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.74'])[1]/following::span[2]</value>
      <webElementGuid>cf0290a8-892e-4b72-8e24-bc24c71b16a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faded Short Sleeve T-shirts'])[2]/preceding::span[1]</value>
      <webElementGuid>67b7553d-4bb5-4d85-a9fb-425a2486a0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU : demo_1'])[1]/preceding::span[1]</value>
      <webElementGuid>22736f43-e60f-490d-96d7-da4ea4ac7f52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$19.25']/parent::*</value>
      <webElementGuid>cdc6e829-5d5d-42a9-8c32-e05d1dd7a7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span</value>
      <webElementGuid>d89dab48-d31a-4156-bc76-841df4604f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'total_price' and (text() = '$19.25' or . = '$19.25')]</value>
      <webElementGuid>aab4317f-8b43-4725-8edc-427d6687489a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
